### ISSUE TITLE
Return value of pocketmine\item\Item::parseCompoundTag() must be an instance of pocketmine\nbt\tag\CompoundTag, instance of pocketmine\nbt\tag\EndTag returned.

### ISSUE THREAD

**Issue by eqMFqfFd** [JackNoordhuis/PocketMine-Plugins#1]

**Comment by kenygamer** [comment]
Plugin: ExplosiveArrows

**Comment by JackNoordhuis** [comment]
Fixed in ee684accc059693b89bb7b04be92b922f7298104, you can get a phar from [poggit](https://poggit.pmmp.io/ci/JackNoordhuis/PocketMine-Plugins/ExplosiveArrows).
