### ISSUE TITLE
Logger bypass

### ISSUE THREAD

**Issue by isoz** [JackNoordhuis/PocketMine-Plugins#13]
Players can bypass by doing /    spawn, adding spaces.

**Comment by ItsMax123** [comment]
Yes true very ennoying

**Comment by Hzste** [comment]
how to stop it?

**Comment by ItsMax123** [comment]
I found a fix please DM me on discord ItsMax123#5571 so I can help you.

**Comment by mrpwes** [comment]
PocketMine-Plugins/CombatLogger/resources/Settings.yml

**Comment by JackNoordhuis** [comment]
Should be fixed in bdfcbd2f560d8b68a1da5cfa712acd43af636fe1
