### ISSUE TITLE
Another bypass glitch

### ISSUE THREAD

**Issue by Hzste** [JackNoordhuis/PocketMine-Plugins#15]
players can bypass by doing /spawn\

**Comment by mrpwes** [comment]
.....

**Comment by mrpwes** [comment]
PocketMine-Plugins/CombatLogger/resources/Settings.yml

**Comment by Hzste** [comment]
> PocketMine-Plugins/CombatLogger/resources/Settings.yml

Yes in the config you can choose which commands to block in combat but say for example I choose to block /spawn in the config it would be - spawn but players can type /spawn\ and bypass it

**Comment by Veixlix** [comment]
https://github.com/Ignaciox/Combat-logger 
fixed issue here

**Comment by JackNoordhuis** [comment]
Should be fixed by bdfcbd2f560d8b68a1da5cfa712acd43af636fe1.
