### ISSUE TITLE
player tag

### ISSUE THREAD

**Issue by SuperAlecs** [JackNoordhuis/PocketMine-Plugins#2]
Can you add when player hit another player and they still are tagged the cooldown will restart?

**Comment by JackNoordhuis** [comment]
Fixed in f7e4e56eadb6105b9055a8c1fd1b4079d58a2f22, you can get a phar from [poggit](https://poggit.pmmp.io/ci/JackNoordhuis/PocketMine-Plugins/CombatLogger).
