### ISSUE TITLE
CombatLogger Crash

### ISSUE THREAD

**Issue by YHC2538** [JackNoordhuis/PocketMine-Plugins#4]
CrashDump:

PocketMine-MP Crash Dump Sun Sep 24 07:21:52 UTC 2017

Error: Declaration of jacknoordhuis\combatlogger\TaggedHeartbeatTask::onRun($currentTick) must be compatible with pocketmine\scheduler\Task::onRun(int $currentTick)
File: CombatLogger/src/jacknoordhuis/combatlogger/TaggedHeartbeatTask
Line: 0
Type: E_COMPILE_ERROR

THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN: CombatLogger v0.0.3

Code:
[1] <?php
[2] 
[3] /**
[4]  * CombatLogger plugin for PocketMine-MP
[5]  * Copyright (C) 2017 JackNoordhuis
[6]  *
[7]  * This program is free software: you can redistribute it and/or modify
[8]  * it under the terms of the GNU Lesser General Public License as published by
[9]  * the Free Software Foundation, either version 2 of the License, or
[10]  * (at your option) any later version.

Backtrace:

PocketMine-MP version: 1.6.2dev #0 [Protocol 134; API 3.0.0-ALPHA7]
Git commit: 0000000000000000000000000000000000000000
uname -a: Windows NT EL_WHITENB 10.0 build 14393 (Windows 10) AMD64
PHP Version: 7.0.13
Zend version: 3.0.0
OS : WINNT, win

Loaded plugins:
AdvancedKits 5.2 by luca28pet for API(s) 3.0.0-ALPHA7
AntiSpamPro 1.4.0-dev1 by awzaw for API(s) 3.0.0-ALPHA7
BanItem 2.3.2-dev by LDX for API(s) 3.0.0-ALPHA7
EconomyAPI 5.7.1-dev2 by onebone for API(s) 3.0.0-ALPHA7
DevTools 1.12.3.2 by PocketMine Team for API(s) 3.0.0-ALPHA7, 3.0.0-ALPHA8
BuycraftPM 0.4.1 by Tebex Limited for API(s) 2.0.0, 3.0.0, 3.0.0-ALPHA4, 3.0.0-ALPHA5, 3.0.0-ALPHA6, 3.0.0-ALPHA7
CombatLogger 0.0.3 by Jack Noordhuis for API(s) 2.0.0, 3.0.0-ALPHA6, 3.0.0-ALPHA7
KillMoney 1.1.3 by kenygamer for API(s) 3.0.0-ALPHA7, 3.0.0-ALPHA8
ShieldPlus 1.0.0 by DarkYusuf13 for API(s) 3.0.0-ALPHA5, 3.0.0-ALPHA6, 3.0.0-ALPHA7

----------------------REPORT THE DATA BELOW THIS LINE-----------------------

===BEGIN CRASH DUMP===
eNrNWntz2za2/yoYpTObdEQ9/YjV9b3jjZ02u35oY2eyd8tOBiIhiTVJsARoWdnpd9/fOQApUnHa
bm7+2DxGxAFwcN4PkP/q2SRTvdn4cHQ0mR4fjyf9nipLXfZm/+rZbYGp3sWHVzdX8zeXFx8u3r69
edvr9zJljFzR3LmKUllKm+hc6KX4WUb3udZlvK4SE4aRzhbSpnq1UmUY3kn8xj8oWdqFkvZOmvvZ
TOdvq/z5N1FVliq3d0l0/0JklbFioQS2F0C9SJXYJHYtCh3dK5sluQpDE61VXKUO7w5RklvRQQZq
l0lKpL5iYi6ZmKEpo2GH2GGb1uETpAJRipN7s9Gv/V6RVqsk30OKFZGOFUlujKk//2+xLgCb4Bk/
U/wMv/0WTwd4Et+K9lbhEIqlLsWcubzCWcHVHMsP6+XFtkxWayuev3ohJqPxsfgrGLiuGcDKI16J
h2O35W6dGFGUelXKTOBxWSoljF7ajSzVTGx1JSKZi1LFibFlsqisEokVMo+HoCPTcbLcAttLhw0z
VR6DVrtWwqoyM6RxGnx//U5cwiQw973KVSlTMa8WaRKJyyRSuVFCgg6CGChNLAjpiUNK218TWbee
LPFa4xQ2qL5Q0DqQPqjSkIFN6gM92r7QJPTxyOF6Li3xVApd0PYXYGQrUml3GAY96M6WMoKSfvyp
31s5akljuSQ36O0L32/EzHhwNJjE6gHARZWkMQwBdlBqqyMNDOPpQb8niwQrp4PRYBScXc5/ODvG
6lViARz9wT/YUMr7NFnQnsHLwRiAyhP3PsljvTHi+k5cXH54/8Obu4vrv4gxThNMkhgfTE+m4nm9
bjx6Ic6uzo8OgINscdY7BmnjKYYfVR7XpLrZD9rQEW+ur+8A4MEGJt4YuyEpncUPMo9U/LfEmpbU
OuC20A4HE4xlZde6xIYfe2kVycnLQtneT15cP3blBbDKJVwe5NmyUv1erAoQa5zGyHrP24BMsh+2
KQjDKwLCX7UkJuc3t3fvb95engO0UQuTWKJ5bW1hZsMh1LOuFgO4/7AhbthhCCI4y21yW8hsXuo2
2y1o11QOwBBsZdxlXm4+ys1XZpxxhqEEKQakwCDDsEvXb0qBmPuLzN9YlbUYqyFtpiaD6WASOAdo
8XR5/o+vzBEwhqGn4ItVCSTB1av5xbBmBXxeRDrX2fZs/qbFagvYNdzjwZi43bNfnasF/n9llj3W
MFSOGqAOww5lv6vEc/Vwp3Xa9soG1LXNMWuyy9Yu7Ik7JbPPsddvD19+Kbc1XWHYotAzeHt39vbu
3fz31Lujd9jgIEuutlEpl3Z+1TbmHbAtiBGcdM8/79RCPSK5ZDg3bslg4qPktP3rhHDQHR52h0fd
4RfbR81CGO4Yh4/UjLli5A8YSada2Ulor4hpy2g0mHZlRDWH2BUdnxHS12X/N6vKPeJ/VwZ/S9L0
Cs62bQlgB9tzlX3u71W+XWFP+QUespSp+aMcN+eEYUPbF8fCBtmwyLIi8Ol8uEj1YphJg/pouBMA
JHS7TlQaw6rawaQF7MrIab0lo3NZ3v9fZaolCo0npfSfOMl/IrTWwWG4o/ePya33K1U6aGUyBYHU
J6kSrA6QVAtV2kRRUfRs3oxQk+fLZCWowQjLMH92W+XiVhViciBGx7PJeHY4Ee/uXnG1TgsybeNT
ct7XVMjPLwjmzghIzJ+ZKnRpT8cn4+mEcahMl9sgpSh1ejgaXRGQ1It6XZ2OeIl8hJblFnycjhmC
0mCTB1Stqohq49NgTODNGswDlbGnerkkiBN88Eulyu2pzlugEunIQ+hxUEhjNvDJ02/5T5jLPEfp
Hil/dCAjqOBBZejETI1epqneBMuUeKxhjjaZJxl03QVmetFA0BoBd8Ooh65lGUe6bMbFQ+GJRPOy
TKIqtdtT5tXV+laXgVHWJvnKnBI4BYmpkz64SeMdzCgVt5ZQM3x6fvH67N3lHbNSWR0Y+aD8eTqn
9jDYacFrLylOKYziLwEfErUJqN2i8vL0JYGo/G4a28E2S8nIBNksGmCyr8r312Rmn3aIMDs0egpN
Vs2XoDaK2iQ4tMED2qKIlMM9dZJHaRWjCwP6T8ybcN3qTPk+ax+nkUvquagnM9w5Lkol713P5XCJ
ZOn6xoRPgGZKGFy6JcTXatOgG8ZqKaEbIzY6/xNazqJAry1IphmYjWAnW5APIqhtJb43a5WLqkAr
GwPBIMxJwA7ZLMzFs7s1usggBQhUpDJfVXJFNwixE5lXhkkwTjXwJx9ZqLT11VpFnovuRhBQh1OV
DzbJfVKgVZYDXa6GNBpeQpEf9PLDm9ubD0fTk2DygfZBjA2imQgRzFZhjw56v1bcz1oNevJYgEtB
jTfJF11pbqhZjd00S5MpBR14UpZViooUva9Yo0dPWclZyLcGcI3dkRw0ATfryqIRhB+5+xoi5tZh
jlJtVOzIOiOnFBQFQIm/iTDiIZHi7xQGsITDQZ04ZoJSN228XWOfJCs1GtT4U5yqZH2lURkYIeI3
DIG5Qz2LlcgWMclpNxGArAWI2qG/4MBT4wHHgjydLjRgEUTqYiu8HWG5D1PN7E4Mz94ju0GZMCkZ
x6JUxlkekQlbuwc50lQlRyq6JlkokgeErn6pZErqWCUPWPsg00qJ5/5IBPUXQO7OQ3hUFKYDaJMK
kRlm6eTrKltA2nCnM7PNI7pHgsWX93CgAc2/gxLYPmsmadW6ROFfwSSw2vQFhyXhwxdfi9C9GLjg
OxESC7IYwbIqh+fQEsZ9yyYDfuBcpX5EeLUKIgA7bOp5QxpJ1ZHzZkkeSkvIE/sisX+C5GzJu2JF
yYOtcG+veA4OoGcxIYkwD4HncsaYyFtd3mJf/R6VBwRLeVw4sOB0RjEpUyu52FoQJG4dKSM+PDGk
Xufp4GmTMGEsbEE5xadFDzIsl2UCc0GYQvzOGRVfgPkTnfrBTMVGu9LgQz/w9VZClrliIl2enYlR
yKGCo7JFqJHxfzn5VBP9BvGUN/9fxBurCz7fh6qGHo/NCLgU1QiIMp4aOrMmaTyaHDiq5qpMNKcj
8kVDB0YckD11jb+NcRRCTUw2xisC+INynsZhXOcIYPBQyI2iw+fE6sSJ0iflCE++7paFnHAJB7xv
58kuHNEJNxRCKMPx8sGni4ltX7pChIWKKBEaFgvR6mTs9jYMQJKqMDs2pyPPp3nxJEGe66njeiXL
BfQfRDpNXWlHHvakVNmciBS/R/g9dNUr84pTbpsKlCMVbOFFv44Je8bgrcHF1eWyjg3ZzsoG4sbl
Ox7BIta6SuOGkAQRZJOLHelkt6JgysHg0WjkeBTPXrMnfBIb2Vbc7oapZamzOsTSXj8ftKNSS6dg
wqtu3xSesJ/WPiqxo3WV3xsnb7404IDIQKKM2g3iRrh6uM/uWaIAMW5RQDUA1TI7XISqVrN3lJMj
T+e5dtv21cdvXvJ6WxuDO8Uv+wo8cyIKItT1ynHtbaE+iCaa7P2bqMI8V5Z00ZRuMI3UZUI082gc
qBCRVOUiAcKefFRiB3SFqZ91wci/K6KcyOHmWTt81TPk+OXWEu6+CMYtY6bcx8cGtiYFYeXwyEWV
Xa7lRoASXezCnVeg2wugp2kgfkB/A/GeohaG4b6av+tjLyhYIP5sktiuXdRm/27QB4x+Jo59YbAr
GQwLprV0IM5i+NNapsshinxXxcQKduYPwpHO/nTedsgmO7dwteqki0dyPiqDZNp3jk0H+9cJAwGz
UWzalOvfzfN5XSnsanYqgmjTBrE+pII9LwI/bNdkaM/Uolo59WsfMwVli5INWj2qqHLFDgUfelsx
aGYNWQTXMMW6GCR5QmSMff3yP2JMdYtPUlSg8kl1ccp7KUz5ojX0Wp05BK7kNGKIBs1WsL3hKnJa
QoiMzU5W6DTZq2eugdAoXMkm6vJe1aUrrRGxtBLN04NrXOipaZJpaucXdePZ6WtUXeSSXCFp19Hx
Um/+lfFFdwQlW/YAvyVwW2Yiw9TK9zuQEl++kQzgEta4oCk7+BHZqWO0rePBl/2UGo4hbFrPrm/u
LmburSP++bewMApClGRFyhU2k+dPbshrTPCsY00R+hxEOs8rWzmnTFBCVm3Jsicjn+Io1LrMSWZO
3TnBfbr0UakLrmOsq9VvKZwQgwtpVOuw52M48hOn9MUEE+OnJpSNBi84qBjVpoJtjF5Lc+vnr2iE
QuB051Fp4jTJTfau+6ZAxV0aVXdkQzLdyK1xuD2elnN18gub0Vmmq7ydoIyvKWsiiHzCRi0N7JIe
Z+Lg81tlSe9pHe0ORzcrivHJ5MndbF25cn3uQjlsC7WkSMm3PhRRSQ0NVncX1ArNLjLfwo1gtAgK
CbXzitrDYlu/Ina5sim4OJAt+bKzDts+zC6rlJdpA1MNyO+TyKU6bhFLui+w/Kq7FtXPmjo15xtG
ZmQrGcdySoAN/3vKIIHWyriSj0LuywU9WsT5a2cPXV2wkb6VcVKZ1javB1nHGnJSt9XbHa1HNUWB
jm7dgqpAzFGtUBalSrpD+CZwF40c4bvGs6Z98CnxPqhuZMJ3CL9UqlJev34/uz3DAwNlzcTLL8JW
6KJKPTb/TKlzD3GYs08GhQvQ7m4xYDsyJEkSZYYEYOlKyEPHPjxQdJ4JV3zWKoWE8qpAMeYqUmeQ
HDxcIeRxAcsx7fIHEtJDGm7oG4SgATJMZosElu+W+NtEd4cwc8GIrjtKadbCQV0N4I3EWa/vNJrg
RnYd0AVUF9Kkkw4UqTPJl3pnBmtNuucjB637SBRqTF+u821GbQh7iIF8TUMo9VV+WuymmWBOfXK1
QvbxlxfNtRDVsPQtxv3T3Dh6CJ15ih6SlzNlVvH+btiEm505BZR54DP+rkJlqC5aF1qv6E6TL9lU
qgvKVn2MwQHdINq6VETltEQlryBs5Kecigda5FNrRdqBP7aQ1J+ftAqTCgWxsS7B1QHPYyMNueka
v9kTymazeUokaYJ047Ry8Sgp37oBVUHA74mY1dTwFIydOvmZ+JGrEiSZPrf2PxFGFwXrMqR9G8xM
1P2Mayrr63Uu2J66XObmm7OY4YqB2M5QSCQg1Kf4Ful8KhPAT4Ju48l1OSXtTpuJ15dnd7PJd8f9
w5PHcX/6OO1Pvht/FyMTu6j13JYKA0SY05cjsYJ9Gzc6OHzBl+/q0aqcBMKvu14hD7U/lFlEKEfW
bQhdyeaxLDsw/6lcAyDTa4+XSWpVZ8sajuZeoGGQUEHUnv3Z7L4koQ/uonJb2PaC2/lle1hEXbLf
qqVvDttQ40r+DshKYiZuw7Kt+SXl74P8kzikKf76QwT0NutwdDA6xuM3b6hTOhhLNRqdvDyJxycn
h8tltFgsj6bx4fHJycH0aHq4lMuTk+OJ+Aa4rb5XOeJ0RxYfk8K9b50O6OXgR/f5UzON4SO/FtmJ
V2f0ScpoNB2PJycAzM9v2vPzNeuH3knTlw63XH3+46ojsj2Umzh+3JumlqlLKICbMtnT5Hsl7xES
+H25+7ICpW/6iUCTjtgxtmrKe479VzWGXdp0Ni7c+4E2bCuZ8Pp9e+FvV/hrrvHgiL9CzD7E2iIu
tPetOjr+JyWYmzknuB3811//DXtWS0o=
===END CRASH DUMP===

**Comment by JackNoordhuis** [comment]
This plugin has been moved to it's [own repo](https://github.com/JackNoordhuis/Battles] and this crash is caused by an outdated or modified version of PocketMine-MP.
