### ISSUE TITLE
CombatLogger : Update Alpha 10

### ISSUE THREAD

**Issue by teracube** [JackNoordhuis/PocketMine-Plugins#6]
Please Update Alpha 10 CombatLogger

**Comment by JackNoordhuis** [comment]
Feel free to try the latest build from [poggit](https://poggit.pmmp.io/ci/JackNoordhuis/PocketMine-Plugins/CombatLogger). I haven't had time to test it yet but everything should be working.

**Comment by teracube** [comment]
@JackNoordhuis
it’s seem ok
thank you
