### ISSUE TITLE
You can do /\ to bypass this

### ISSUE THREAD

**Issue by artulloss** [JackNoordhuis/PocketMine-Plugins#7]
You can do any command starting like /\ to bypass CombatLogger
example: /\hub /\tp /\warp
Please fix this, tested on another server with this plugin and it is bypassable

**Comment by artulloss** [comment]
Yea fixed it myself by doing that however it is a problem you should make sure people know about, I noticed it's doable on several large servers

**Comment by JackNoordhuis** [comment]
I tweeted out that I updated the plugin with a critical bug fix update, hopefully most people using the plugin will find out about the update.
